# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# ダブルクオーテーションを使う
Style/StringLiterals:
  EnforcedStyle: double_quotes

# インデントは2スペース
Layout/IndentationWidth:
  Enabled: true
  Width: 2

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: normal
